

spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      enabled: true
      # 파일 사이즈 체크
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 300
        jdbc:
          batch_size: 10000
#          배치처리
  profiles:
    include: prd, jwt, oauth, google
  data:
    redis:
      host: localhost
      port: 6379
  messages:
    basename: messages,errors

com:
  example:
    ex8_fileupload:
      upload:
        path: /Users/imhaneul/files/image
server:
  port: 80


management:
  endpoints:
    web:
      exposure:
        include: health, info # 필요한 엔드포인트만 노출
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

