spring:
  datasource:
    url: jdbc:mysql://mungwithme-rds.cdukqi2ouosv.ap-northeast-2.rds.amazonaws.com/mungwithme
    username: admin
    password: ajddnltal!23
    driver-class-name: com.mysql.cj.jdbc.Driver