server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: db, jwt, oauth
  data:
    redis:
      host: localhost
      port: 6379

com:
  example:
    ex8_fileupload:
      upload:
        path: /your/desired/path

