name: Build and Deploy for BACKEND server to AWS EC2

on:
  push:
    branches: [develop]

env:
  PROJECT_NAME: BE_Server
  BUCKET_NAME: mungwithme-github-action-s3-bucket
  CODE_DEPLOY_APP_NAME: mungwithme-app
  DEPLOYMENT_GROUP_NAME: mungwithme-app-deployment-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create and populate application YAML files
      run: |
        echo "${{ secrets.APPLICATION_DB }}" > ./src/main/resources/application-db.yml
        echo "${{ secrets.APPLICATION_JWT }}" > ./src/main/resources/application-jwt.yml
        echo "${{ secrets.APPLICATION_OAUTH }}" > ./src/main/resources/application-oauth.yml
        echo "${{ secrets.APPLICATION_GOOGLE }}" > ./src/main/resources/application-google.yml

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Make Zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: |
        aws deploy create-deployment \
          --application-name $CODE_DEPLOY_APP_NAME \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
